ManufacturedMotion/Hexapod

HexapodController/User_mapped_zero_position.ino, HexapodController/axis.cpp, HexapodController/axis.hpp, HexapodController/config.cpp, HexapodController/config.hpp
added header files & arduino example code for moving all motors to user mapped zero position.
edited axis header files to have a default constructor for "Axis" object
=> User mapped values

.gitmodules
Reverts ManufacturedMotion/Hexapod#40
=> Revert "Update .gitmodules"

.gitmodules
Reverts ManufacturedMotion/Hexapod#41
=> Revert "Revert "Update .gitmodules""

Raspberry Pi/rpi_setup.md, Raspberry Pi/testing_serial.ino, Raspberry Pi/testing_serial.py
Update serial example to link properly and use 115200 baud rate instead of 9600
=> Update serial example

Raspberry Pi/rpi_setup.md, Raspberry Pi/web_interface/app.py, Raspberry Pi/web_interface/templates/index.html
Create a Flask Web Interface for Interacting with Serial
To-Do:
- Update formatting to follow standards
- Remove unnecessary comments
=> Create a Flask Web Interface for Interacting with Serial

Raspberry Pi/controller_config.py, Raspberry Pi/controller_test.py, Raspberry Pi/rpi_setup.md
Add controller testing code and documentation
=> Add controller testing code

Raspberry Pi/main.py, Raspberry Pi/templates/index.html, Raspberry Pi/webserver_setup.py
Fix Serial output and other nits
=> Fix Serial output and other nits

Raspberry Pi/main.py
Fix serial parsing so two leading spaces are no longer necessary
=> Update serial send for reliability

Raspberry Pi/controller_setup.py
Add in G0 from the controller as J1 Push
=> Add in G0 from the controller as J1 Push

Mk2/main.py
Remove webserver dependency for code in Mk2
=> remove webserver dependency

mk2/electronics/hexapod_mk2_leg_v0.0.b##
Add draft cad for Mk2
Missing lid, s1, s2, s3 refinements
=> Add draft cad for Mk2

mk2/electronics/hexapod_mk2_main_v0.0.b##
I finished making all of the changes we scoped out for mk2. I am sure there will be more improvements as we start printing and assembling the design, but this should be the bulk of the CAD re-work.
Once fully built and finalized, I will make a finishing pass at all of the assemblies (some are now broken) and do general cleanups of the CAD timelines + files. Plus will make a more detailed CAD assembly (we're missing some connectors, for example).
=> Add "final" assembly of mk2

.gitignore, mk2/code/real_time/teensy_code/.gitignore, mk2/code/real_time/teensy_code/lib/HexapodController/TEMPLATE_user_config.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/user_config.hpp
=> Fix git ignore

mk2/code/real_time/teensy_code/lib/HexapodController/src/config.hpp, mk2/code/real_time/teensy_code/src/main.cpp
add logic to read vsense pin, convert it to 12V scale and echo it to serial output
=> add vsense logic to main

mk2/code/non_real_time/pi5_setup.md, mk2/code/non_real_time/setup.sh
update setup script with better commenting and to auto install led ring dependencies
=> Setup script updates

mk2/code/real_time/teensy_code/lib/HexapodController/src/axis.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/config.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/gcode_parser.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/gcode_parser.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/hexapod.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/hexapod_controller.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/json_joints.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/json_parser.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/json_parser.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/serial_parser.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/serial_parser.hpp, mk2/code/real_time/teensy_code/src/main.cpp
move string parsing code from main.cpp into distinct header files. The code has been separated into 3 files; serial parsing, json parsing, and gcode parsing. The serial parser handles all commands received via serial and redirects them to either the json parser or the gcode parser based on the command format. 
Gcode parsing code is primarily used as a tool for ease of debug (easier to type with the lack of curly braces). When the DEBUG flag is set to false in the user_config.hpp file, the gcode parsing code is excluded and therefore does not get compiled.
=> String parsing

mk2/code/real_time/teensy_code/lib/HexapodController/src/gcode_parser.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/gcode_parser.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/json_parser.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/json_parser.hpp
change uint16_t -> uint32_t so we can call legEnqueue
=> fix for legEnqueue function calls

mk2/code/non_real_time/container/src/ros2_ws/src/gait/gait/teensy_gait.py, mk2/code/non_real_time/container/src/ros2_ws/src/gait/package.xml, mk2/code/non_real_time/container/src/ros2_ws/src/gait/setup.cfg, mk2/code/non_real_time/container/src/ros2_ws/src/gait/setup.py, mk2/code/non_real_time/container/src/ros2_ws/src/gait/test/test_copyright.py, mk2/code/non_real_time/container/src/ros2_ws/src/gait/test/test_flake8.py, mk2/code/non_real_time/container/src/ros2_ws/src/gait/test/test_pep257.py, mk2/code/non_real_time/container/src/ros2_ws/src/teensy_node/teensy_node/uart_teensy.py, mk2/code/real_time/teensy_code/lib/HexapodController/src/hexapod.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/serial_parser.cpp, mk2/code/real_time/teensy_code/src/main.cpp
functional walking via xbox controller inputs
=> Controller walking

mk2/code/non_real_time/container/src/ros2_ws/src/hexapod_manager/hexapod_manager/led_controller.py
=> Add Missing LED Functionality

mk2/code/non_real_time/container/resources/example_script.txt, mk2/code/non_real_time/container/src/ros2_ws/resources/example_script.txt, mk2/code/non_real_time/container/src/ros2_ws/src/hexapod_manager/hexapod_manager/run_from_file.py
support to send commands to teensy via a txt file
`python3 src/hexapod_manager/hexapod_manager/run_from_file.py resources/example_script.txt`
=> Pi scripting

mk2/code/non_real_time/container/src/ros2_ws/src/gait/gait/teensy_gait.py, mk2/code/real_time/teensy_code/lib/HexapodController/src/serial_parser.cpp
pi gets ack from teensy after sending a move command. The ack is how much time it takes to execute the motion. The pi waits this amount of time before sending the next command
=> Move time updates

mk2/code/non_real_time/container/src/ros2_ws/src/gait/gait/teensy_gait.py, mk2/code/real_time/teensy_code/lib/HexapodController/src/serial_parser.cpp
Reverts ManufacturedMotion/Hexapod#235
reopening the PR for more review / testing on other bots
=> Revert "Move time updates"

mk2/code/real_time/teensy_code/src/main.cpp
fix that stops main loop from writing empty commands to the queue
=> Serial spam fix

mk2/code/non_real_time/container/src/ros2_ws/src/gait/gait/teensy_gait.py, mk2/code/real_time/teensy_code/lib/HexapodController/src/serial_parser.cpp
Reverts ManufacturedMotion/Hexapod#236
=> Revert "Revert "Move time updates""

mk2/code/real_time/teensy_code/lib/HexapodController/src/config.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/hexapod.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/log_levels.hpp
Also adds in missing file for log level definitions
=> Dillon gobilda servo calibration. 

mk2/code/non_real_time/container/src/ros2_ws/src/hexapod_manager/hexapod_manager/display.py, mk2/code/non_real_time/container/src/ros2_ws/src/hexapod_manager/hexapod_manager/led_controller.py, mk2/code/non_real_time/container/src/ros2_ws/src/hexapod_manager/launch/user_controlled.yml
- Updated LED handling to resolve #224 . This also required pretty significant timing changes to the Led file.
- Launch the display as part of `user_controlled.yml`
=> Update LED Handling

mk2/code/non_real_time/container/docker-compose-prod.yml, mk2/code/non_real_time/container/init_prod.sh, mk2/code/non_real_time/container/install.sh, mk2/code/non_real_time/container/src/entry_point.sh, mk2/code/non_real_time/container/stop_prod.sh
Initial reboot setup, this doesn't fully work because of the screen so the retry call is commented out.
=> Initial reboot setup

mk2/code/real_time/teensy_code/lib/HexapodController/src/config.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/hexapod.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/hexapod.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/serial_parser.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/step_queue.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/step_queue.hpp
Creates new commands "DNCE" and "FDNC" that operates a preset routine/dance on the hexapod, DNCE is done at 100mm/s, while FDNC is done at 300mm/s
Also added in absolute linear moves to the step queue for proper implementation of a couple of the moves too.
=> add dance command and update config

mk2/code/non_real_time/cron_jobs/start_container/cronjob, mk2/code/non_real_time/cron_jobs/start_container/start_container, mk2/code/non_real_time/setup.sh
=> start container on boot

mk2/code/real_time/teensy_code/lib/HexapodController/src/axis.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/axis.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/hexapod.cpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/hexapod.hpp, mk2/code/real_time/teensy_code/lib/HexapodController/src/serial_parser.cpp
=> Add Detach Servo Functionality

mk2/code/non_real_time/container/src/ros2_ws/src/gait/gait/teensy_gait.py
Add button to call the detach servo preset from the xbox controller
=> Detach button control
